import sys

filepath = r'app\src\main\java\com\dmb\bestbefore\ui\screens\profile\ProfileScreen.kt'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = '        // 1. HALLWAY (Main Page)\n        // Show only if no overlay step'
end_marker   = '        // 2. ALL SECTION (Picture Gallery)'

start_idx = content.find(start_marker)
end_idx   = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print(f'ERROR: markers not found. start={start_idx} end={end_idx}')
    sys.exit(1)

new_hallway = (
    '        // 1. HALLWAY -- SwiftUI HallwayView component\n'
    '        // Visible when no overlay step is active\n'
    '        AnimatedVisibility(\n'
    '            visible = currentStep == ProfileStep.NONE && !isAllMediaVisible,\n'
    '            enter = fadeIn(),\n'
    '            exit = fadeOut()\n'
    '        ) {\n'
    '            val currentTab by hallwayViewModel.currentTab.collectAsState()\n'
    '            val notifRepo = remember { com.dmb.bestbefore.data.repository.NotificationRepository(context) }\n'
    '            val unreadCount by notifRepo.unreadCount.collectAsState()\n'
    '            val hallwayRefreshing by hallwayViewModel.isRefreshing.collectAsState()\n'
    '\n'
    '            androidx.compose.material3.pulltorefresh.PullToRefreshBox(\n'
    '                isRefreshing = hallwayRefreshing,\n'
    '                onRefresh = { hallwayViewModel.refreshRooms() },\n'
    '                modifier = Modifier.fillMaxSize()\n'
    '            ) {\n'
    '                Box(modifier = Modifier.fillMaxSize()) {\n'
    '\n'
    '                    // SwiftUI-ported HallwayView: tag chips, card stack, artist info, bottom nav\n'
    '                    com.dmb.bestbefore.ui.components.HallwayView()\n'
    '\n'
    '                    // Top-right icons requiring ProfileViewModel context\n'
    '                    Row(\n'
    '                        modifier = Modifier\n'
    '                            .fillMaxWidth()\n'
    '                            .windowInsetsPadding(WindowInsets.statusBars)\n'
    '                            .padding(end = 8.dp, top = 20.dp)\n'
    '                            .align(Alignment.TopEnd),\n'
    '                        horizontalArrangement = Arrangement.End,\n'
    '                        verticalAlignment = Alignment.CenterVertically\n'
    '                    ) {\n'
    '                        if (currentTab == BottomTab.ROOMING) {\n'
    '                            IconButton(onClick = {\n'
    '                                val hasCam = androidx.core.content.ContextCompat.checkSelfPermission(\n'
    '                                    context, android.Manifest.permission.CAMERA\n'
    '                                ) == android.content.pm.PackageManager.PERMISSION_GRANTED\n'
    '                                if (hasCam) {\n'
    '                                    val intent = android.content.Intent(\n'
    '                                        context,\n'
    '                                        com.dmb.bestbefore.ui.screens.profile.QrScannerActivity::class.java\n'
    '                                    )\n'
    '                                    qrScanLauncher.launch(intent)\n'
    '                                } else {\n'
    '                                    qrCameraPermissionLauncher.launch(android.Manifest.permission.CAMERA)\n'
    '                                }\n'
    '                            }) {\n'
    '                                Icon(Icons.Default.QrCodeScanner, contentDescription = "Scan QR",\n'
    '                                    tint = Color.White, modifier = Modifier.size(24.dp))\n'
    '                            }\n'
    '                        }\n'
    '                        IconButton(onClick = { showMusicSelector = true }) {\n'
    '                            Icon(Icons.Default.MusicNote, contentDescription = "Music",\n'
    '                                tint = Color.White, modifier = Modifier.size(24.dp))\n'
    '                        }\n'
    '                        Box(\n'
    '                            modifier = Modifier.size(48.dp)\n'
    '                                .clickable { notifRepo.markAllRead(); onNavigateToNotifications() },\n'
    '                            contentAlignment = Alignment.Center\n'
    '                        ) {\n'
    '                            Icon(Icons.Default.Notifications, contentDescription = "Notifications",\n'
    '                                tint = Color.White, modifier = Modifier.size(24.dp))\n'
    '                            if (unreadCount > 0) {\n'
    '                                Box(\n'
    '                                    modifier = Modifier.align(Alignment.TopEnd)\n'
    '                                        .offset(x = 4.dp, y = 4.dp).size(16.dp)\n'
    '                                        .background(Color.Red, CircleShape),\n'
    '                                    contentAlignment = Alignment.Center\n'
    '                                ) {\n'
    '                                    Text(\n'
    '                                        if (unreadCount > 9) "9+" else unreadCount.toString(),\n'
    '                                        color = Color.White, fontSize = 9.sp, fontWeight = FontWeight.Bold\n'
    '                                    )\n'
    '                                }\n'
    '                            }\n'
    '                        }\n'
    '                    }\n'
    '\n'
    '                    // Bottom: music mini-player + tab navigation\n'
    '                    Column(modifier = Modifier.align(Alignment.BottomCenter)) {\n'
    '                        com.dmb.bestbefore.ui.components.MusicPlayerBottomBar(modifier = Modifier.padding(bottom = 4.dp))\n'
    '                        BottomNavigation(\n'
    '                            currentTab = currentTab,\n'
    '                            onTabSelected = {\n'
    '                                if (it == BottomTab.EVERYONE) viewModel.closeOverlay()\n'
    '                                hallwayViewModel.selectTab(it)\n'
    '                            },\n'
    '                            onProfileClick = { viewModel.openProfileMenu() },\n'
    '                            modifier = Modifier\n'
    '                                .windowInsetsPadding(WindowInsets.navigationBars)\n'
    '                                .padding(bottom = 16.dp)\n'
    '                        )\n'
    '                    }\n'
    '\n'
    '                    // OrbMenu: room creation + profile menu shortcut\n'
    '                    val themeColors = LocalBestBeforeColors.current\n'
    '                    OrbMenu(\n'
    '                        modifier = Modifier.align(Alignment.CenterEnd),\n'
    '                        primaryColor = themeColors.primary,\n'
    '                        secondaryColor = themeColors.secondary,\n'
    '                        onAddClick = { viewModel.startCreateRoom(RoomCreationSource.HALLWAY) },\n'
    '                        onProfileClick = { viewModel.openProfileMenu() },\n'
    '                        onSearchClick = { },\n'
    '                        onChatClick = { }\n'
    '                    )\n'
    '                }\n'
    '            }\n'
    '        }\n'
    '\n'
)

new_content = content[:start_idx] + new_hallway + content[end_idx:]

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(new_content)

print('Done! ProfileScreen.kt rewritten successfully.')
